macro(install_shaders SHADER_LIST PLUG LIB_NAME)
    string(TOUPPER ${PLUG} PLUG_UPPER)
    foreach(ITEM IN LISTS ${SHADER_LIST})
        if(DO_DEBUG)
            set(LOC "Debug")
        else()
            set(LOC "Release")
        endif()
        set(INST_LOC "shaders")
        #install(FILES "${ITEM}"
        #        DESTINATION ${INST_LOC})
    endforeach()
    target_compile_definitions(${LIB_NAME} PUBLIC -DSHADER_FOLDER_${PLUG_UPPER}=\"${INST_LOC}\")
endmacro()
